### ISSUE TITLE
Properly manage duplicate keyring entries

### ISSUE THREAD

**Issue by rudi-cilibrasi** [iov-one/bcp-redux#139]
When the user enters the same mnemonic and adds passphrase twice (from the set Active Account dialog), the GUI displays two keyring entries.

This seems incorrect.

Especially since they have the same Id and the redux store holds everything by Id. So it seems we are not deduplicating at the iov-core level. The user of the GUI wallet app certainly should be protected from this confusing situation.

**Comment by webmaster128** [comment]
Good point, but not sure how to solve this.

On the IOV-Core level, there is no definition of equality of keyring entries, so there is no trivial way to deduplicate them. Given that there is more data in a keyring entry than the secret, two keyring entries with the same secret and different labels or different identities would not be equal. This makes all kind of set structures useless.

Since secret is a private field, currently there is also no way for the UI to do this test itself. Maybe we can implement and expose a test like "entry x has same secret as entry y", but this will not be easy for Ledger (or at least requires to create an identity and compare pubkeys).

> Especially since they have the same Id and the redux store holds everything by Id. 

I consider this a bug in the ID generation. At core level, there should not be a restriction to add different entries with the same secret.

**Comment by webmaster128** [comment]
In https://github.com/iov-one/iov-core/pull/349 (will be part of @iov/core 0.6.x) all entry IDs become auto-generated. An ID remains the same when an entry is cloned or saved/loaded. The ID does not tell anything about the secret. So two entries can have the same secret but will have distinct IDs.

Checking if two entries have the same secret is a different topic: it can be done but we should have an explicit API for that. This is not yet present.
