### ISSUE TITLE
Clarify use of combineReducers

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-redux#28]
I'm trying to catch up on the architecture, so some basic questions that might have reasons, but still were a bit surprising:

https://redux.js.org/api/combinereducers#example shows that each reducer only gets a subset of the state-space and they are combined by placing each reducer as a different element in a map, prefixed by it's name.

In `index.mjs`, they are nicely combined:

```
  const blockchainReducer = combineReducers({
    height,
    blockPeriodEstimator,
    txById,
    balanceByAddress,
  });
```

And `height.mjs` shows just keeping an integer for the state, which then ends up as `{ height: n}` in the final state returned by combineReducers:

```
function height(state = -1, action) {
  if (action.type == `${INITIALIZE_READER_FOR_CHAINID}_${FULFILLED}` ||
      action.type == `${FETCH_HEIGHT_FOR_CHAINID}_${FULFILLED}`) {
    const { height } = action.payload;
    return height;
  }
  return state;
}
```

so far, this looks good and makes sense to me. However, the more complex reducers use a different approach:

```
function balanceByAddress(state = { byAddress: { } }, action) {
...
  return { byAddress: newByAddress };
}
```

```
function txById(state = { byTxId: { } }, action) {
...
  return { byTxId: newByTxId };
}
```

This means I would have to do `state.balanceByAddress.byAddress[addr]` to get the balance, which seems unnecessarily wordy. I would expect `balanceByAddress` to return the map itself, not an object with map as an arguement. Then again, maybe you wanted to add more info there rather than just one map (i dunna, total balance over all addresses as a state variable?).

I would recommend either:

`state.balanceByAddress[addr]` if we don't want to extend it beyond one map (update reducer) `state.balance.byAddress[addr]` if we will want to expand it later, then top-level is just balance, and we just update the name it is registered on in combineReducers.

Can you explain the design choice and provide a clearer naming for these elements?

**Comment by rudi-cilibrasi** [comment]
https://redux.js.org/api/combinereducers is the API we are using ; it is clear and well documented and old and well tested.

the names are the reason i brought you in. we obviously have bad names in the old reducers; they are singleton groups with no properties. the hardest part of the new reducer shape (and only creative part besides the actual structure) is the naming. I don't think we can address the naming problem by "wishing" for better names and ignoring the practice required to use _other_ libraries.

When we have enough reducers restructured cleanly we will be able to make names that are appropriate to distinguish their different functions. This is not a combineReducers problem this is naming problem in bcp-redux.

The suggestion you gave: ```state.balanceByAddress[addr] if we don't want to extend it beyond one map (update reducer) ``` is actually not a 2-level reducer. It suffers the same problem as all our old reducers: it exists as a bag of one item. You would need another level of indirection in there in order to use `combineReducers` twice. WIthout using `combineReducers` more than once you don't have your reducers organized into (more than one) group. In other words the organization you describe is where we are coming from not going to in the simplified case.  The second one (what you call balance) is not just balance. It's properties. Again, `blockchain` is public immutable data. `purseNonSense` is personal information (that could mutate more normally) that is stored persistently between app runs, `transient` is not stored. and `purseSense` which will be stored encrypted on disk. So no, it's not _just balance_ and this is the point of the refactoring.
